import { CheatFeature } from '@/types/cheat';

export const generateReadme = (cheatName: string, currentCheat: CheatFeature[]): string => {
  const byCategory = currentCheat.reduce((acc, f) => {
    if (!acc[f.category]) acc[f.category] = [];
    acc[f.category].push(f);
    return acc;
  }, {} as Record<string, CheatFeature[]>);

  return `# ${cheatName}
> Professional Minecraft Java Edition Cheat Client

## ✨ Features (${currentCheat.length} modules)

${Object.entries(byCategory).map(([cat, mods]) => `### ${cat}
${mods.map(m => `- **${m.name}** ${Object.keys(m.settings).length > 0 ? `- \`${Object.entries(m.settings).map(([k,v]) => `${k}=${v}`).join(', ')}\`` : ''}`).join('\n')}`).join('\n\n')}

## 🎮 Controls

| Key | Action |
|-----|--------|
| **Right Shift** | Open ClickGUI menu |
${currentCheat.slice(0, 10).map(f => `| **${f.name.charAt(0).toUpperCase()}** | Toggle ${f.name} |`).join('\n')}

## 🔧 Building

### Requirements:
- Java JDK 17+
- Gradle 7.6+
- Minecraft Forge 1.19.2

### Build steps:
\`\`\`bash
# Windows
.\\gradlew.bat build

# Linux/Mac
./gradlew build
\`\`\`

Output: \`build/libs/${cheatName}-1.0.0.jar\`

## 📦 Installation

1. Install Minecraft Forge 1.19.2 (43.2.0+)
2. Copy JAR to \`.minecraft/mods/\`
3. Launch Minecraft with Forge profile

## 🏗️ Architecture

\`\`\`
${cheatName}/
├── ModuleManager    - Module system core
├── EventManager     - Forge event handling
├── ConfigManager    - Save/load configs
├── ClickGUI         - In-game menu
├── modules/         - All cheat modules
│   ├── combat/
│   ├── movement/
│   ├── render/
│   └── world/
└── utils/           - Helper utilities
\`\`\`

## ⚠️ Disclaimer

**For educational purposes only!** 
- Use only on private servers or singleplayer
- Most servers prohibit cheats - risk of ban
- Author not responsible for consequences

---
🤖 Generated by **Minecraft Cheat Generator AI**  
Based on: Nursultan, Celestial, Vape v4 architecture`;
};
